# Generated by Django 3.2.6 on 2021-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Cleaning and supplies'), ('O', 'Storage Supplies'), ('C', 'Cuttleries'), ('B', 'Bathroom'), ('E', 'Beddings')], max_length=20),
        ),
    ]
