# Generated by Django 3.2.6 on 2021-09-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='name',
            new_name='item_name',
        ),
    ]
