# Generated by Django 3.2.6 on 2021-09-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210914_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
            preserve_default=False,
        ),
    ]
