# Generated by Django 3.2 on 2021-11-12 06:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211005_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Electronics'), ('S', 'Cleaning and supplies'), ('O', 'Storage Supplies'), ('C', 'Cuttleries'), ('B', 'Bathroom'), ('E', 'Beddings')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
