# Generated by Django 3.2.6 on 2021-11-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Electronics'), ('S', 'Cleaning and supplies'), ('O', 'Storage Supplies'), ('C', 'Cuttleries'), ('B', 'Bathroom'), ('E', 'Beddings'), ('G', 'Gas')], max_length=20),
        ),
    ]
